### PR TITLE
#187419123-Feature(Update Password): Logged in Users should be able  to update their Password

### PR DESCRIPTION
**Pull request by Jovz19200**
## what Does this PR do?
- Logged user are able to update their password
## How to test the functionality ?
- Checkout to the preview deployment of this PR
- checkout to the ||   URL/login (login is prerequisite to be able to update the PW)
- checkout to the ||  URL/update-password
- follow the procedure and update the password 
- verify if the password has been updated by perhaps trying to log in again 

## Some of the photos of how feature Interface look like
Screenshot 2024-06-27 at 08 06 38
Screenshot 2024-06-27 at 08 09 25
Screenshot 2024-06-27 at 08 10 19

### CODE REVIEW

**Review by niyobertin — CHANGES_REQUESTED** [review]
Screenshot 2024-06-25 at 23 10 13

@Jovz19200  your page ins not responsive

**Review by niyobertin — APPROVED** [review]
LGTM

**Comment by Jovz19200** [comment]
> Screenshot 2024-06-25 at 23 10 13
> @Jovz19200 your page ins not responsive

Fixed

**Review by yvanddniyo — APPROVED** [review]
Lgtm

**Pull request merged**
